name: Build & Test package
on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
      - name: Cache the Virtual Env
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('pdm.lock') }}
      - name: Install the project dependencies
        run: pdm install -d
      - name: Build the project
        run: pdm build
      - name: Run the automated tests (for example)
        run: pdm run test -- -v
