name: Build & Test package
on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  create_matrix:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        uses: JLLeitschuh/endoflife-matrix-action@main
        with:
          product: python
    outputs:
      version_matrix: ${{ steps.matrix.outputs.versions }}
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.create_matrix.outputs.version_matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4

      - name: Cache the Virtual Env
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}

      - name: Install the project dependencies
        run: pdm install -d

      - name: Build the project
        run: pdm build

      - name: Run the Unit tests
        run: pdm run test -- -v
