name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4

      - name: Build & Publish package to PyPI
        run: pdm publish
